#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th ite#ration, displays Best School and then Hi on a new line.

num=0

while [[ $num -le 9 ]]
do
	echo "Best School"
	((num++))
	if [[ $num -eq 9 ]]
	then
		echo "Hi"
	fi
done
