#!/usr/bin/bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

hr=0
min=1

while [[ "$hr" -le 12 -a "$hr"  1 ]]
do
	echo "Hour: $hr"
#	((hr++))
	while [[ "$min" -le 59 ]]
	do
		echo "$min"
		((min++))
#		((hr++))
	done
	((hr++))

done
